### ISSUE TITLE
关于运行项目时产生的问题

### ISSUE THREAD

**Issue by 20182131111-zc** [zhangxuying1004/RSTNet#10]
作者您好！很庆幸能看到你的作品！我在自己的电脑调试项目的时候，出现了很多意想不到的问题，我刚接触cv+nlp领域，有些方面还不太了解，想请教一下您
1. readme中提到代码是在python3.6环境下运行的，我使用的是Windows系统的python3.9 是否会因为版本不一样导致运行时报错？

2. 在train_transformer中，dataloader_train函数中shuffle如果为true，会产生ValueError: DataLoader with IterableDataset: expected unspecified shuffle option, but got shuffle=True    
 把shuffle改成false之后，会出现下面的报错（ File "E:\Anaconda\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: 'generator' object is not callable），想问问是否是上面的版本系统不兼容的问题引起的呢？
![b0588fe5f3cb01e22d5a03ccf0ffb52](https://user-images.githubusercontent.com/71591305/135035325-bf5975a5-95b1-49e2-9b0f-ac4f7f7788a0.png)

3. X-101_features中使用的是关于2014和2015的pth文件，在这个条件下用自己的数据集（例如说COCO2017版本的数据集）会不会有影响，如果要用自己的数据集需要进行什么修改吗？

期待作者您的回复，非常感谢！

**Comment by zhangxuying1004** [comment]
> 作者您好！很庆幸能看到你的作品！我在自己的电脑调试项目的时候，出现了很多意想不到的问题，我刚接触cv+nlp领域，有些方面还不太了解，想请教一下您
> 
> 1. readme中提到代码是在python3.6环境下运行的，我使用的是Windows系统的python3.9 是否会因为版本不一样导致运行时报错？
> 2. 在train_transformer中，dataloader_train函数中shuffle如果为true，会产生ValueError: DataLoader with IterableDataset: expected unspecified shuffle option, but got shuffle=True
>    把shuffle改成false之后，会出现下面的报错（ File "E:\Anaconda\lib\multiprocessing\reduction.py", line 60, in dump
>    ForkingPickler(file, protocol).dump(obj)
>    TypeError: 'generator' object is not callable），想问问是否是上面的版本系统不兼容的问题引起的呢？
>    ![b0588fe5f3cb01e22d5a03ccf0ffb52](https://user-images.githubusercontent.com/71591305/135035325-bf5975a5-95b1-49e2-9b0f-ac4f7f7788a0.png)
> 3. X-101_features中使用的是关于2014和2015的pth文件，在这个条件下用自己的数据集（例如说COCO2017版本的数据集）会不会有影响，如果要用自己的数据集需要进行什么修改吗？
> 
> 期待作者您的回复，非常感谢！

您好，感谢您的关注。
1 & 2. 应该不是环境问题，您check一下这这dataloader中的dataset有没有问题。
3. 可以使用自己的数据集，需要在相同配置下提取您的的数据集的特征，提取方式可以参考我学弟的代码：https://github.com/rentainhe/TRAR-Feature-Extraction。

**Comment by 20182131111-zc** [comment]
> > 作者您好！很庆幸能看到你的作品！我在自己的电脑调试项目的时候，出现了很多意想不到的问题，我刚接触cv+nlp领域，有些方面还不太了解，想请教一下您
> > 
> > 1. readme中提到代码是在python3.6环境下运行的，我使用的是Windows系统的python3.9 是否会因为版本不一样导致运行时报错？
> > 2. 在train_transformer中，dataloader_train函数中shuffle如果为true，会产生ValueError: DataLoader with IterableDataset: expected unspecified shuffle option, but got shuffle=True
> >    把shuffle改成false之后，会出现下面的报错（ File "E:\Anaconda\lib\multiprocessing\reduction.py", line 60, in dump
> >    ForkingPickler(file, protocol).dump(obj)
> >    TypeError: 'generator' object is not callable），想问问是否是上面的版本系统不兼容的问题引起的呢？
> >    ![b0588fe5f3cb01e22d5a03ccf0ffb52](https://user-images.githubusercontent.com/71591305/135035325-bf5975a5-95b1-49e2-9b0f-ac4f7f7788a0.png)
> > 3. X-101_features中使用的是关于2014和2015的pth文件，在这个条件下用自己的数据集（例如说COCO2017版本的数据集）会不会有影响，如果要用自己的数据集需要进行什么修改吗？
> > 
> > 期待作者您的回复，非常感谢！
> 
> 您好，感谢您的关注。 1 & 2. 应该不是环境问题，您check一下这这dataloader中的dataset有没有问题。 3. 可以使用自己的数据集，需要在相同配置下提取您的的数据集的特征，提取方式可以参考我学弟的代码：[https://github.com/rentainhe/TRAR-Feature-Extraction。](https://github.com/rentainhe/TRAR-Feature-Extraction%E3%80%82)

感谢回复！上述问题已经解决了！但是您发的链接点进去404了，能有别的参考一下吗？

**Comment by zhangxuying1004** [comment]
> > > 作者您好！很庆幸能看到你的作品！我在自己的电脑调试项目的时候，出现了很多意想不到的问题，我刚接触cv+nlp领域，有些方面还不太了解，想请教一下您
> > > 
> > > 1. readme中提到代码是在python3.6环境下运行的，我使用的是Windows系统的python3.9 是否会因为版本不一样导致运行时报错？
> > > 2. 在train_transformer中，dataloader_train函数中shuffle如果为true，会产生ValueError: DataLoader with IterableDataset: expected unspecified shuffle option, but got shuffle=True
> > >    把shuffle改成false之后，会出现下面的报错（ File "E:\Anaconda\lib\multiprocessing\reduction.py", line 60, in dump
> > >    ForkingPickler(file, protocol).dump(obj)
> > >    TypeError: 'generator' object is not callable），想问问是否是上面的版本系统不兼容的问题引起的呢？
> > >    ![b0588fe5f3cb01e22d5a03ccf0ffb52](https://user-images.githubusercontent.com/71591305/135035325-bf5975a5-95b1-49e2-9b0f-ac4f7f7788a0.png)
> > > 3. X-101_features中使用的是关于2014和2015的pth文件，在这个条件下用自己的数据集（例如说COCO2017版本的数据集）会不会有影响，如果要用自己的数据集需要进行什么修改吗？
> > > 
> > > 期待作者您的回复，非常感谢！
> > 
> > 
> > 您好，感谢您的关注。 1 & 2. 应该不是环境问题，您check一下这这dataloader中的dataset有没有问题。 3. 可以使用自己的数据集，需要在相同配置下提取您的的数据集的特征，提取方式可以参考我学弟的代码：[https://github.com/rentainhe/TRAR-Feature-Extraction。](https://github.com/rentainhe/TRAR-Feature-Extraction%E3%80%82)
> 
> 感谢回复！上述问题已经解决了！但是您发的链接点进去404了，能有别的参考一下吗？

https://github.com/rentainhe/TRAR-Feature-Extraction

**Comment by qwerty3564** [comment]
怎么解决的

**Comment by ZouChuang711** [comment]
已收到，谢谢
