### ISSUE TITLE
关于特征处理

### ISSUE THREAD

**Issue by TBI805** [zhangxuying1004/RSTNet#13]
师兄您好，非常有幸能看到您团队的这篇工作，我对该工作非常有兴趣，但是在制作hdf5特征时遇到了一些问题，特此想请教一下您：
       我在解压了X-101-features.tgz后，运行feats_process.py时遇到了一点意外。程序报错截图如下，请问如何解决呢？
       非常期待您的回复，感谢！
![Screenshot from 2021-11-03 22-21-35](https://user-images.githubusercontent.com/34084035/140080592-2d3a6ee0-865d-4bf0-a9b8-3bf1cc210da6.png)

**Comment by HN123-123** [comment]
您好，请问你的问题解决了吗，我在处理这个特征的时候也遇到类似错误，路径下确定可以查到改文件，但处理时报错找不到文件。可以分享一下您的解决方案吗？？非常感谢！

**Comment by TBI805** [comment]
> 您好，请问你的问题解决了吗，我在处理这个特征的时候也遇到类似错误，路径下确定可以查到该文件，但处理时报错找不到文件。可以分享一下您的解决方案吗？？非常感谢！

@HN123-123 抱歉，我目前还没有解决。但我发现可以使用DLCT中的grid特征，可以作为一个临时的替代方案。

**Comment by HN123-123** [comment]
> > 您好，请问你的问题解决了吗，我在处理这个特征的时候也遇到类似错误，路径下确定可以查到该文件，但处理时报错找不到文件。可以分享一下您的解决方案吗？？非常感谢！
> 
> @HN123-123 抱歉，我目前还没有解决。但我发现可以使用DLCT中的grid特征，可以作为一个临时的替代方案。

这个文件找不到的问题我解决了，它在读取特征的时候只读到了文件名，
![f3ff1768c68411e0c6ba5052faf1b09](https://user-images.githubusercontent.com/54923253/143367365-62f03be3-c948-4589-b939-3830fec7159a.png)
在这里添加绝对路径可以读取特征。我现在还没有处理完，所以还不太清楚最终文件是否能用。

还有一个问题，我也看DLCT的特征了，作者提供的hdf5特征文件中含有集中不同属性特征，您在用的时候是从中提取grid特征另外生成特征文件还是直接从源文件中指定特征读入，如果是指定的话，想知道您是如何实现的。

**Comment by TBI805** [comment]
> 
> 
> 
> > > 您好，请问你的问题解决了吗，我在处理这个特征的时候也遇到类似错误，路径下确定可以查到该文件，但处理时报错找不到文件。可以分享一下您的解决方案吗？？非常感谢！
> > 
> > @HN123-123 抱歉，我目前还没有解决。但我发现可以使用DLCT中的grid特征，可以作为一个临时的替代方案。
> 
> 这个文件找不到的问题我解决了，它在读取特征的时候只读到了文件名，
> ![f3ff1768c68411e0c6ba5052faf1b09](https://user-images.githubusercontent.com/54923253/143367365-62f03be3-c948-4589-b939-3830fec7159a.png)
> 在这里添加绝对路径可以读取特征。我现在还没有处理完，所以还不太清楚最终文件是否能用。
> 
> 还有一个问题，我也看DLCT的特征了，作者提供的hdf5特征文件中含有集中不同属性特征，您在用的时候是从中提取grid特征另外生成特征文件还是直接从源文件中指定特征读入，如果是指定的话，想知道您是如何实现的。

@HN123-123 我直接从coco_all_align中指定特征读入的，具体的实现可以参考DLCT中data/filed.py 的148行左右的preprocess函数，我把precom_data后的features改为了grids。但这样后面的数据流好像会出问题。
后来看了RST的field.py，可以直接拿过来用。特征直接放coco_all_align.hdf5就可以了。

**Comment by HN123-123** [comment]
谢谢谢谢

**Comment by zhangxuying1004** [comment]
> > 您好，请问你的问题解决了吗，我在处理这个特征的时候也遇到类似错误，路径下确定可以查到该文件，但处理时报错找不到文件。可以分享一下您的解决方案吗？？非常感谢！
> 
> @HN123-123 抱歉，我目前还没有解决。但我发现可以使用DLCT中的grid特征，可以作为一个临时的替代方案。

已修复这个文件的bug，并且上传了本人处理好的视觉特征。
