### ISSUE TITLE
关于 SPICE 分数

### ISSUE THREAD

**Issue by amazingYX** [zhangxuying1004/RSTNet#14]
非常感谢你能开源论文的代码。但是在 evaluation 中，并没有计算 spice 分数的相关代码，我想知道你是如何得到 spice 分数的？

**Comment by zhangxuying1004** [comment]
> 非常感谢你能开源论文的代码。但是在 evaluation 中，并没有计算 spice 分数的相关代码，我想知道你是如何得到 spice 分数的？

您好，这里把spice部分去掉的原因是训练过程中计算spice太耗时，模型训练好以后，测试时加上即可。把https://github.com/ruotianluo/coco-caption/tree/ea20010419a955fed9882f9dcc53f2dc1ac65092/pycocoevalcap这个链接下的spice文件夹放到evaluation文件夹下，并在__init__.py中把spice引入即可。

**Comment by zhangxuying1004** [comment]
> 非常感谢你能开源论文的代码。但是在 evaluation 中，并没有计算 spice 分数的相关代码，我想知道你是如何得到 spice 分数的？

您好，这里把spice部分去掉的原因是训练过程中计算spice太耗时，模型训练好以后，测试时加上即可。把https://github.com/ruotianluo/coco-caption/tree/ea20010419a955fed9882f9dcc53f2dc1ac65092/pycocoevalcap，这个链接下的spice文件夹放到evaluation文件夹下，并在__init__.py中把spice引入即可。

**Comment by zhangxuying1004** [comment]
> 非常感谢你能开源论文的代码。但是在 evaluation 中，并没有计算 spice 分数的相关代码，我想知道你是如何得到 spice 分数的？

您好，这里把spice部分去掉的原因是训练过程中计算spice太耗时，模型训练好以后，测试时加上即可。把https://github.com/ruotianluo/coco-caption/tree/ea20010419a955fed9882f9dcc53f2dc1ac65092/pycocoevalcap 这个链接下的spice文件夹放到evaluation文件夹下，并在__init__.py中把spice引入即可。

**Comment by amazingYX** [comment]
> > 非常感谢你能开源论文的代码。但是在 evaluation 中，并没有计算 spice 分数的相关代码，我想知道你是如何得到 spice 分数的？
> 
> 您好，这里把spice部分去掉的原因是训练过程中计算spice太耗时，模型训练好以后，测试时加上即可。把https://github.com/ruotianluo/coco-caption/tree/ea20010419a955fed9882f9dcc53f2dc1ac65092/pycocoevalcap 这个链接下的spice文件夹放到evaluation文件夹下，并在__init__.py中把spice引入即可。

非常感谢，这对我帮助很大！

**Comment by amazingYX** [comment]
你好，非常抱歉，再次打扰你。我对于 beamsearch.py 中对 visual 进行 expand 的操作不是很理解，visual 只是当  t=0 时，作为 encoder 的输入，得到 self.enc_output，decoder 的输入也只有 self.enc_output。对 self.enc_output 进行 expand 后，visual 感觉就没有必要再进行处理了，为什么要多此一举？
