### ISSUE TITLE
特征下载

### ISSUE THREAD

**Issue by HN123-123** [zhangxuying1004/RSTNet#15]
您好，非常感谢您能开源论文的代码。您提供的X-101-features特征有326G, 我下载时总是因为网络中断而下载失败，请问您有百度网盘版的特征链接吗？

**Comment by zhangxuying1004** [comment]
> 您好，非常感谢您能开源论文的代码。您提供的X-101-features特征有326G, 我下载时总是因为网络中断而下载失败，请问您有百度网盘版的特征链接吗？

抱歉哈，前段时间在考英语没有及时回复。这个特征我也是直接下载的。不过，我这边有处理好7x7大小的X101特征，好像是30多个G，我这几天想办法上传上去，你如果需要的话，可以使用这个。
