### ISSUE TITLE
测试过程

### ISSUE THREAD

**Issue by lc080113** [zhangxuying1004/RSTNet#18]
非常高兴看到您出色的工作，给我带来了很大帮助。在测试阶段我遇到了一个问题，在训练阶段，预训练语言模型通过融合所有前文来预测下一个单词，但是在测试中模型似乎只能通过上一步的一个单词来预测，不知道是不是我的理解有误，如果确实是这样，这种测试方法是否会降低影最终的效果？

**Comment by zhangxuying1004** [comment]
> 

您好，抱歉哈，我前段时间在考英语，没有及时回复。关于您的问题，“在测试中模型似乎只能通过上一步的一个单词来预测”，这句话理解有偏差，测试阶段确实是一个单词一个单词地预测，但是在预测每一个单词时，使用的都是已生成的所有前文信息，而不是只有上一个单词的信息，这一点Transformer与RNN都是一样的逻辑，您可以再看一下测试阶段的代码。

**Comment by zhangxuying1004** [comment]
> 非常高兴看到您出色的工作，给我带来了很大帮助。在测试阶段我遇到了一个问题，在训练阶段，预训练语言模型通过融合所有前文来预测下一个单词，但是在测试中模型似乎只能通过上一步的一个单词来预测，不知道是不是我的理解有误，如果确实是这样，这种测试方法是否会降低影最终的效果？

您好，抱歉哈，我前段时间在考英语，没有及时回复。关于您的问题，“在测试中模型似乎只能通过上一步的一个单词来预测”，这句话理解有偏差，测试阶段确实是一个单词一个单词地预测，但是在预测每一个单词时，使用的都是已生成的所有前文信息，而不是只有上一个单词的信息，这一点Transformer与RNN都是一样的逻辑，您可以再看一下测试阶段的代码。
