### ISSUE TITLE
about original paper

### ISSUE THREAD

**Issue by wanboyang** [zhangxuying1004/RSTNet#2]
Thank you for opening sources.
Could you provide the paper for this project?

**Comment by zhangxuying1004** [comment]
> Thank you for opening sources.
> Could you provide the paper for this project?

Thanks for your attention, our paper is coming soon after the patent application.

**Comment by zhangxuying1004** [comment]
> Thank you for opening sources.
> Could you provide the paper for this project?

You can now download our paper through the paper link in readme

**Comment by wanboyang** [comment]
Thanks

**Comment by harshraj22** [comment]
@zhangxuying1004  where is the supplementary material that you talk about in [section 3.1](https://openaccess.thecvf.com/content/CVPR2021/papers/Zhang_RSTNet_Captioning_With_Adaptive_Attention_on_Visual_and_Non-Visual_Words_CVPR_2021_paper.pdf) about specific calculations of 2d relative position of each grid ?
