### ISSUE TITLE
关于ensemble模型

### ISSUE THREAD

**Issue by TBI805** [zhangxuying1004/RSTNet#21]
您好，我在您所开源的代码中注意到有‘’TransformerEnsemble‘’这个类，请问应该如何使用它训练及测试指定数量的ensemble模型呢（比如指定模型是 ensemble 2 或者ensemble 4）？

**Comment by zhangxuying1004** [comment]
> 您好，我在您所开源的代码中注意到有‘’TransformerEnsemble‘’这个类，请问应该如何使用它训练及测试指定数量的ensemble模型呢（比如指定模型是 ensemble 2 或者ensemble 4）？

这个类只在测试时使用，集成多个模型的结果。您可以参考test_online/test_online.py，这里面使用了这个类。
