### ISSUE TITLE
寻求处理后的7*7的X-101特征文件

### ISSUE THREAD

**Issue by wxzasdf** [zhangxuying1004/RSTNet#22]
尊敬的作者您好，您的这篇文章非常棒，我在复现的时候发现您分享的X-101特征文件实在太大了，您可否分享一下您处理后的特征文件呢，我看您在其它issue里说您处理后的特征文件大概30-50G，您可否通过百度网盘或者谷歌网盘分享一下呢，您如果空间不够的话我可以给您提供足够大的云盘账号，非常感谢！

**Comment by haijie945** [comment]
同求一份特征文件，300多G太大了

**Comment by zhangxuying1004** [comment]
> 同求一份特征文件，300多G太大了

我没有足够大小的谷歌网盘。如果急用的话，可以跟楼上的王同学一样，把U盘寄给我，我拷好特征发给您。

**Comment by haijie945** [comment]
已给您发送gmail，请您看下

**Comment by wanboyang** [comment]
> 
请问您得到处理后的特征了吗

**Comment by zhangxuying1004** [comment]
> hasky123

没有收到您的邮件。。。

**Comment by zhangxuying1004** [comment]
急用这个特征的话，可以加一下我的微信，zhangxuying1004
