### ISSUE TITLE
spice分数评估失败

### ISSUE THREAD

**Issue by haijie945** [zhangxuying1004/RSTNet#23]
您好，我在使用spice评估时，调用spice-1.0.jar包时总会发生CalledProcessError的错误，很疑惑
![image](https://user-images.githubusercontent.com/69234726/155881570-6e25a186-e846-43a4-9413-afaf1be9898a.png)

**Comment by zhangxuying1004** [comment]
> 您好，我在使用spice评估时，调用spice-1.0.jar包时总会发生CalledProcessError的错误，很疑惑 ![image](https://user-images.githubusercontent.com/69234726/155881570-6e25a186-e846-43a4-9413-afaf1be9898a.png)

可以检查一下您下载的spice-1.0.jar有没有问题，java环境有没有问题，或者去coco官网看看。
