### ISSUE TITLE
只生成<'unk'>，无法生成其他单词

### ISSUE THREAD

**Issue by jianqingxie** [zhangxuying1004/RSTNet#24]
你好，我运行 test.py 文件时，模型只会生成 <'unk'> tokens，没有其他单词，请问是什么原因呢

**Comment by zhangxuying1004** [comment]
> 你好，我运行 test.py 文件时，模型只会生成 <'unk'> tokens，没有其他单词，请问是什么原因呢

训练时没问题吧？那就检查一下test.py模型加载，特征加载对应的文件和代码。

**Comment by jianqingxie** [comment]
> > 你好，我运行 test.py 文件时，模型只会生成 <'unk'> tokens，没有其他单词，请问是什么原因呢
> 
> 训练时没问题吧？那就检查一下test.py模型加载，特征加载对应的文件和代码。

你好，应该是python版本的问题，beam_search.py文件的118行应该把 / 改成 // 吧？python3除法是会有小数的，这样会使得selected_words一直是0
