### ISSUE TITLE
About how to get the caption of a input pic with my own pretrained model.

### ISSUE THREAD

**Issue by z972778371** [zhangxuying1004/RSTNet#26]
Hello, thanks for sharing your code!
But I wonder how to get a image's caption like figure 1(b) or 6 in your artical 
Could you share me the code ?
Thanks a lot!

**Comment by z972778371** [comment]
I can get the output token through the variable caps_gen,but I don't know which image the caption corresponds to.
I also want to know how can i get the caption of a causal image instead of the coco image loaded by dataloader function.

**Comment by zhangxuying1004** [comment]
> I can get the output token through the variable caps_gen,but I don't know which image the caption corresponds to. I also want to know how can i get the caption of a causal image instead of the coco image loaded by dataloader function.

you can refer to the blow code in test_online.py.
![image](https://user-images.githubusercontent.com/47649909/168028323-38540531-5ad6-4543-b88a-2a2ed437d7a2.png)
