### ISSUE TITLE
您好，能不能把预训练好的bert_language模型给我分享一下，我下不了（跪求）

### ISSUE THREAD

**Issue by zjq0917** [zhangxuying1004/RSTNet#28]
$ wget https://drive.google.com/file/d/1sayx7qwOd79XE4RFdvSXG3zyQH4FpyYJ/view?usp=sharing
--2022-03-23 18:09:05--  https://drive.google.com/file/d/1sayx7qwOd79XE4RFdvSXG3zyQH4FpyYJ/view?usp=sharing
Resolving drive.google.com (drive.google.com)... 31.13.95.37, 2001::68f4:2b68
Connecting to drive.google.com (drive.google.com)|31.13.95.37|:443... failed: Connection timed out.
Connecting to drive.google.com (drive.google.com)|2001::68f4:2b68|:443... failed: Network is unreachable.
，网盘账号是15603379965

**Comment by zhangxuying1004** [comment]
> $ wget https://drive.google.com/file/d/1sayx7qwOd79XE4RFdvSXG3zyQH4FpyYJ/view?usp=sharing --2022-03-23 18:09:05-- https://drive.google.com/file/d/1sayx7qwOd79XE4RFdvSXG3zyQH4FpyYJ/view?usp=sharing Resolving drive.google.com (drive.google.com)... 31.13.95.37, 2001::68f4:2b68 Connecting to drive.google.com (drive.google.com)|31.13.95.37|:443... failed: Connection timed out. Connecting to drive.google.com (drive.google.com)|2001::68f4:2b68|:443... failed: Network is unreachable. ，网盘账号是15603379965

您可以加一下我的微信，账号见project主页。
