### ISSUE TITLE
RuntimeError: gather(): Expected dtype int64 for index

### ISSUE THREAD

**Issue by zhuhaifengaaa** [zhangxuying1004/RSTNet#29]
When I run train_transformer.py, I'm having difficulty, showing **RuntimeError: gather(): Expected dtype int64 for index**, can anyone tell me how to solve it? 
thank you very much
![Quicker_20220407_164612](https://user-images.githubusercontent.com/69130513/162159506-6a28e1a1-077c-4df0-9776-84e3eec62251.png)

**Comment by zhangxuying1004** [comment]
> When I run train_transformer.py, I'm having difficulty, showing **RuntimeError: gather(): Expected dtype int64 for index**, can anyone tell me how to solve it? thank you very much ![Quicker_20220407_164612](https://user-images.githubusercontent.com/69130513/162159506-6a28e1a1-077c-4df0-9776-84e3eec62251.png)

我没有遇到过这个问题哈，可能是由于某一步的浮点运算出错导致的bug，建议您check一下您的pytorch版本，我使用的是torch==1.1.0

**Comment by yiren-jian** [comment]
For latest version of pytorch, for most (if not all) `torch.gather()` in `models/beam_search/beam_search.py`, you need to add `.long()`
