### ISSUE TITLE
关于实验结果

### ISSUE THREAD

**Issue by pp-cv** [zhangxuying1004/RSTNet#3]
你好，你所的工作很不错，对此很感兴趣。但是我按照你所给的提示运行了代码，在在RL训练前是没有问题的，但是进行RL训练后模型的性能急剧下降，最终的cider为0.009，我不清楚是那里出现问题了，能否给一些意见

**Comment by zhangxuying1004** [comment]
感谢您的关注。有两点需要check一下。
一是特征的获取，下载完X-101-features.tgz，使用feats_process处理，确保这一步没问题。
二是语言模型的预训练，我微调之后，test_score为57%多点，val_score为58%多点。
这两步确认以后再跑RSTNet。

**Comment by sisiypappy** [comment]
你好，我也有遇到了同样的问题，进入RL之后性能急剧下降，cider也差不多是0.009，并且一个epoch的时间从几十分钟到了七八小时。在此之前，我check了以上两点，不知是否还有其他一些需要注意的问题？

**Comment by pp-cv** [comment]
我用了作者所提供的模型第二步预训练也没有达到这个结果test_score为57%多点，val_score为58%多点。

**Comment by zhuhaifengaaa** [comment]
> 我用了作者所提供的模型第二步预训练也没有达到这个结果test_score为57%多点，val_score为58%多点。

请问，你解决这个问题了吗

**Comment by zhangxuying1004** [comment]
我把rstnet训练过程的tensorboard文件上传到tensorboard_logs文件夹中了，大家可以在训练过程中可视化对照一下，check一下是哪个阶段出现的问题。
