### ISSUE TITLE
请问，为什么强化学习阶段训练损失是负数啊？

### ISSUE THREAD

**Issue by zhuhaifengaaa** [zhangxuying1004/RSTNet#32]
请问，为什么强化学习阶段训练损失是负数啊？

![Quicker_20220424_095834](https://user-images.githubusercontent.com/69130513/164952628-8bb9c73a-dce6-44b7-8aab-76a2acb7c131.png)

**Comment by zhangxuying1004** [comment]
> 请问，为什么强化学习阶段训练损失是负数啊？
> 
> ![Quicker_20220424_095834](https://user-images.githubusercontent.com/69130513/164952628-8bb9c73a-dce6-44b7-8aab-76a2acb7c131.png)

我没遇到过这个问题，请问您训练时，交叉熵阶段是正常的吗？

**Comment by zhangxuying1004** [comment]
我把我当时训练rstnet过程的tensorboard文件上传到这个project了，建议您可视化对照一下。

**Comment by zhuhaifengaaa** [comment]
> 我把我当时训练rstnet过程的tensorboard文件上传到这个project了，建议您可视化对照一下。

好的，多谢学长

**Comment by LeXueTao** [comment]
> 请问，为什么强化学习阶段训练损失是负数啊？
> 
> ![Quicker_20220424_095834](https://user-images.githubusercontent.com/69130513/164952628-8bb9c73a-dce6-44b7-8aab-76a2acb7c131.png)

您好，您这个问题解决了吗？
