### ISSUE TITLE
数据集特征提取

### ISSUE THREAD

**Issue by moment-ggw** [zhangxuying1004/RSTNet#33]
您好请问可以您提取grid特征的代码是基于https://github.com/rentainhe/TRAR-Feature-Extraction 这个项目做的么，如果不是的话可以分享一下您提取grid特征的代码么

**Comment by zhangxuying1004** [comment]
> 您好请问可以您提取grid特征的代码是基于https://github.com/rentainhe/TRAR-Feature-Extraction 这个项目做的么，如果不是的话可以分享一下您提取grid特征的代码么

这个是我学弟的project，可以使用这里代码提取特征。提取grid特征的原project是https://github.com/facebookresearch/grid-feats-vqa

**Comment by moment-ggw** [comment]
嗯嗯，谢谢你的回答！
我调试过这个项目，但是我发现这里面的coco图片的输入原始大小被resize成了600*800，请问你在处理的过程中是否将图片resize成224*224？

**Comment by zhangxuying1004** [comment]
> 嗯嗯，谢谢你的回答！ 我调试过这个项目，但是我发现这里面的coco图片的输入原始大小被resize成了600×800，请问你在处理的过程中是否将图片resize成224×224？

您好，我没有调试过这个项目，在这篇论文中，我使用他们提取号的COCO特征作为原始特征，并且做了进一步处理。

**Comment by zhangxuying1004** [comment]
> 嗯嗯，谢谢你的回答！ 我调试过这个项目，但是我发现这里面的coco图片的输入原始大小被resize成了600×800，请问你在处理的过程中是否将图片resize成224×224？

您好，我没有调试过这个项目，在这篇论文中，我使用他们提取好的COCO特征作为原始特征，并且做了进一步处理。
