### ISSUE TITLE
我运行训练文件的时候报错TypeError: __init__() got an unexpected keyword argument 'return_dict'

### ISSUE THREAD

**Issue by MrAccelerator** [zhangxuying1004/RSTNet#34]
![图片](https://user-images.githubusercontent.com/56375036/167356384-8311c1a9-449a-4083-9b23-71c1a1ce2220.png)

**Comment by zhangxuying1004** [comment]
> ![图片](https://user-images.githubusercontent.com/56375036/167356384-8311c1a9-449a-4083-9b23-71c1a1ce2220.png)

应该是您安装的transformers包的版本问题，建议check一下。

**Comment by MrAccelerator** [comment]
> > ![图片](https://user-images.githubusercontent.com/56375036/167356384-8311c1a9-449a-4083-9b23-71c1a1ce2220.png)
> 
> 应该是您安装的transformers包的版本问题，建议check一下。

我的transformer包是2.4.1版本

**Comment by MrAccelerator** [comment]
问题解决了，我把transformers升到3.4.0版本就可以了，谢谢老师解答
