### ISSUE TITLE
vocab.pkl

### ISSUE THREAD

**Issue by gjc0824** [zhangxuying1004/RSTNet#38]
Hello，thank you for sharing you code. I have checked the size of vocab.pkl and found that it is 10199 not 10201. I am strange to this field so could you please tell me what the other two token are?

**Comment by zhangxuying1004** [comment]
> Hello，thank you for sharing you code. I have checked the size of vocab.pkl and found that it is 10199 not 10201. I am strange to this field so could you please tell me what the other two token are?

I don't meet this problem, and I don't know how you check this file. 
I check it by the following code to get the size of vocab：
![image](https://user-images.githubusercontent.com/47649909/174718729-0b093bbf-a97d-4d87-85a6-e60065075bff.png)
The output is as follows：
![image](https://user-images.githubusercontent.com/47649909/174719042-56999926-76f4-48ef-bcaa-8e91cbc00043.png)
