### ISSUE TITLE
visualness

### ISSUE THREAD

**Issue by gjc0824** [zhangxuying1004/RSTNet#39]
Hello, I am interested in your visualness word. How will deal with the token that haven't occured for one image?

**Comment by zhangxuying1004** [comment]
> Hello, I am interested in your visualness word. How will deal with the token that haven't occured for one image?

Thanks for your attention. Our visualness is used to reflect the degree to visual information in the image is required to predict a word. As a result, the visualness of the token you mentioned is 0.
