### ISSUE TITLE
Question about the position encoding

### ISSUE THREAD

**Issue by z972778371** [zhangxuying1004/RSTNet#40]
Hello author, thank you very much for sharing your source code with us. I have two questions I would like to ask you about the position encoding in your model.
1. Are the two parts of the image pointed by the red arrow equivalent?
    Position encoding is mentioned only once in the picture，but in the section 3.2 of the paper, there is another position encoding mentioned in Eq. (8).
2. How position encoding is performed?
    In Figure 3 of the paper, Does the position encoding occur between the bert module and the Masked Multi-Head Attention module?
![Resnet](https://user-images.githubusercontent.com/51855588/171861898-48dc8fcc-3a8f-4dac-ba2c-00cf30f3d356.png)
![figure3](https://user-images.githubusercontent.com/51855588/171861964-22a12c26-e240-4331-9515-4eb5d4ed2c87.png)

**Comment by z972778371** [comment]
No position encoding used in the Transformer Architecture, right?

**Comment by zhangxuying1004** [comment]
> Hello author, thank you very much for sharing your source code with us. I have two questions I would like to ask you about the position encoding in your model.
> 
> 1. Are the two parts of the image pointed by the red arrow equivalent?
>    Position encoding is mentioned only once in the picture，but in the section 3.2 of the paper, there is another position encoding mentioned in Eq. (8).
> 2. How position encoding is performed?
>    In Figure 3 of the paper, Does the position encoding occur between the bert module and the Masked Multi-Head Attention module?
>    ![Resnet](https://user-images.githubusercontent.com/51855588/171861898-48dc8fcc-3a8f-4dac-ba2c-00cf30f3d356.png)
>    ![figure3](https://user-images.githubusercontent.com/51855588/171861964-22a12c26-e240-4331-9515-4eb5d4ed2c87.png)

Thanks for your attention.
1. The position encoding in the two parts you mentioned above is the same. You can refer to the 124-th row of `models/rstnet/decoders.py` and the 86-th row of `models/rstnet/language.py`.
The position encoding in Eq. (8) is used to prevent possible position shift caused by bert module.
