### ISSUE TITLE
online特征提取

### ISSUE THREAD

**Issue by Baixiaobai201619707** [zhangxuying1004/RSTNet#41]
您好！请问您是怎么提取的在线特征啊，我在使用[grid-feats-vqa ](https://github.com/facebookresearch/grid-feats-vqa).提取时会报错：
```
[06/16 14:17:39 fvcore.common.checkpoint]: [Checkpointer] Loading from others/X-101.pth ...
Traceback (most recent call last):
  File "/home/bwh/anaconda3/envs/m2release/lib/python3.6/site-packages/detectron2/data/catalog.py", line 55, in get
    f = DatasetCatalog._REGISTERED[name]
KeyError: 'coco_2014_test'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bwh/python/d_3_1/others/extract_region_feature.py", line 139, in <module>
    data_loader = build_detection_test_loader_with_attributes(cfg, dataset_name)
  File "/home/bwh/python/d_3_1/others/grid_feats/build_loader.py", line 88, in build_detection_test_loader_with_attributes
    else None,
  File "/home/bwh/anaconda3/envs/m2release/lib/python3.6/site-packages/detectron2/data/build.py", line 224, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/home/bwh/anaconda3/envs/m2release/lib/python3.6/site-packages/detectron2/data/build.py", line 224, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/home/bwh/anaconda3/envs/m2release/lib/python3.6/site-packages/detectron2/data/catalog.py", line 59, in get
    name, ", ".join(DatasetCatalog._REGISTERED.keys())
KeyError: "Dataset 'coco_2014_test' is not registered! Available datasets are: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_minival_100, coco_2014_valminusminival, coco_2017_train, coco_2017_val, coco_2017_test, coco_2017_test-dev, coco_2017_val_100, keypoints_coco_2014_train, keypoints_coco_2014_val, keypoints_coco_2014_minival, keypoints_coco_2014_valminusminival, keypoints_coco_2014_minival_100, keypoints_coco_2017_train, keypoints_coco_2017_val, keypoints_coco_2017_val_100, coco_2017_train_panoptic_separated, coco_2017_train_panoptic_stuffonly, coco_2017_val_panoptic_separated, coco_2017_val_panoptic_stuffonly, coco_2017_val_100_panoptic_separated, coco_2017_val_100_panoptic_stuffonly, lvis_v0.5_train, lvis_v0.5_val, lvis_v0.5_val_rand_100, lvis_v0.5_test, lvis_v0.5_train_cocofied, lvis_v0.5_val_cocofied, cityscapes_fine_instance_seg_train, cityscapes_fine_sem_seg_train, cityscapes_fine_instance_seg_val, cityscapes_fine_sem_seg_val, cityscapes_fine_instance_seg_test, cityscapes_fine_sem_seg_test, voc_2007_trainval, voc_2007_train, voc_2007_val, voc_2007_test, voc_2012_trainval, voc_2012_train, voc_2012_val, visual_genome_train, visual_genome_val, visual_genome_test"
```

**Comment by Baixiaobai201619707** [comment]
> > 您好！请问您是怎么提取的在线特征啊，我在使用[grid-feats-vqa ](https://github.com/facebookresearch/grid-feats-vqa).提取时会报错：
> > ```
> > [06/16 14:17:39 fvcore.common.checkpoint]: [Checkpointer] Loading from others/X-101.pth ...
> > Traceback (most recent call last):
> >   File "/home/bwh/anaconda3/envs/m2release/lib/python3.6/site-packages/detectron2/data/catalog.py", line 55, in get
> >     f = DatasetCatalog._REGISTERED[name]
> > KeyError: 'coco_2014_test'
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "/home/bwh/python/d_3_1/others/extract_region_feature.py", line 139, in <module>
> >     data_loader = build_detection_test_loader_with_attributes(cfg, dataset_name)
> >   File "/home/bwh/python/d_3_1/others/grid_feats/build_loader.py", line 88, in build_detection_test_loader_with_attributes
> >     else None,
> >   File "/home/bwh/anaconda3/envs/m2release/lib/python3.6/site-packages/detectron2/data/build.py", line 224, in get_detection_dataset_dicts
> >     dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
> >   File "/home/bwh/anaconda3/envs/m2release/lib/python3.6/site-packages/detectron2/data/build.py", line 224, in <listcomp>
> >     dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
> >   File "/home/bwh/anaconda3/envs/m2release/lib/python3.6/site-packages/detectron2/data/catalog.py", line 59, in get
> >     name, ", ".join(DatasetCatalog._REGISTERED.keys())
> > KeyError: "Dataset 'coco_2014_test' is not registered! Available datasets are: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_minival_100, coco_2014_valminusminival, coco_2017_train, coco_2017_val, coco_2017_test, coco_2017_test-dev, coco_2017_val_100, keypoints_coco_2014_train, keypoints_coco_2014_val, keypoints_coco_2014_minival, keypoints_coco_2014_valminusminival, keypoints_coco_2014_minival_100, keypoints_coco_2017_train, keypoints_coco_2017_val, keypoints_coco_2017_val_100, coco_2017_train_panoptic_separated, coco_2017_train_panoptic_stuffonly, coco_2017_val_panoptic_separated, coco_2017_val_panoptic_stuffonly, coco_2017_val_100_panoptic_separated, coco_2017_val_100_panoptic_stuffonly, lvis_v0.5_train, lvis_v0.5_val, lvis_v0.5_val_rand_100, lvis_v0.5_test, lvis_v0.5_train_cocofied, lvis_v0.5_val_cocofied, cityscapes_fine_instance_seg_train, cityscapes_fine_sem_seg_train, cityscapes_fine_instance_seg_val, cityscapes_fine_sem_seg_val, cityscapes_fine_instance_seg_test, cityscapes_fine_sem_seg_test, voc_2007_trainval, voc_2007_train, voc_2007_val, voc_2007_test, voc_2012_trainval, voc_2012_train, voc_2012_val, visual_genome_train, visual_genome_val, visual_genome_test"
> > ```
> 
> 我没有用[grid-feats-vqa ](https://github.com/facebookresearch/grid-feats-vqa)中代码提取，而是使用他们提取好的特征，他们提供了coco2015的原始特征。我使用本项目中的`feats_process.py`处理以后便得到了本任务的线上特征。此外，我已经把我提取好的特征放到一个提问者的网盘上，并且在readme中给出了超链接和提取码，你也可以直接使用。
您好，我直接使用了您提供的在线测试特征和预训练模型，发现生成的描述有些是不全的，像是被截断了，请问您遇到过这种情况吗，还是因为我哪里操作不当呢？

**Comment by Baixiaobai201619707** [comment]
@zhangxuying1004 谢谢您！我直接使用了您提供的在线测试特征和预训练模型，发现生成的描述有些是不全的，像是被截断了，请问您遇到过这种情况吗，还是因为我哪里操作不当呢？

**Comment by zhangxuying1004** [comment]
> 

您好，您说的这个情况我也遇到了。主要原因应该是[meshed-memory-transformer](https://github.com/aimagelab/meshed-memory-transformer)提供的这套代码训练模型时，对于每一个句子，没有考虑<eos>，这种方式学得的模型在测试时可能会倾向于生成那些高频/容易预测的单词并且提前结束。

**Comment by Baixiaobai201619707** [comment]
> > @zhangxuying1004 谢谢您！我直接使用了您提供的在线测试特征和预训练模型，发现生成的描述有些是不全的，像是被截断了，请问您遇到过这种情况吗，还是因为我哪里操作不当呢？
> 
> 您好，您说的这个情况我也遇到了。主要原因应该是[meshed-memory-transformer](https://github.com/aimagelab/meshed-memory-transformer)提供的这套代码训练模型时，对于每一个标注的句子，没有考虑，这种方式学得的模型在测试时可能会倾向于生成那些高频/容易预测的单词并且把低频词当成提前结束。

请问您可以提供一下您的解决方案吗？谢谢！

**Comment by zhangxuying1004** [comment]
> > > @zhangxuying1004 谢谢您！我直接使用了您提供的在线测试特征和预训练模型，发现生成的描述有些是不全的，像是被截断了，请问您遇到过这种情况吗，还是因为我哪里操作不当呢？
> > 
> > 
> > 您好，您说的这个情况我也遇到了。主要原因应该是[meshed-memory-transformer](https://github.com/aimagelab/meshed-memory-transformer)提供的这套代码训练模型时，对于每一个标注的句子，没有考虑，这种方式学得的模型在测试时可能会倾向于生成那些高频/容易预测的单词并且把低频词当成提前结束。
> 
> 请问您可以提供一下您的解决方案吗？谢谢！

在模型训练时，对于每一个句子，让解码器的最后一个时间步预测<eos>，即根据 <bos> w_{1} ... w_{len} 依次预测w_{1} ... w_{len} <eos>，而不是现在的<bos> w_{1} ... w_{len-1}到w_{1} ... w_{len}。

**Comment by zhangxuying1004** [comment]
> > > @zhangxuying1004 谢谢您！我直接使用了您提供的在线测试特征和预训练模型，发现生成的描述有些是不全的，像是被截断了，请问您遇到过这种情况吗，还是因为我哪里操作不当呢？
> > 
> > 
> > 您好，您说的这个情况我也遇到了。主要原因应该是[meshed-memory-transformer](https://github.com/aimagelab/meshed-memory-transformer)提供的这套代码训练模型时，对于每一个标注的句子，没有考虑，这种方式学得的模型在测试时可能会倾向于生成那些高频/容易预测的单词并且把低频词当成提前结束。
> 
> 请问您可以提供一下您的解决方案吗？谢谢！

可以试一下，在模型训练时，对于每一个句子，让解码器的最后一个时间步预测，即根据 bos, w_{1} ... w_{len} 依次预测w_{1} ... w_{len}, eos，而不是现在的 bos, w_{1}, ... ,w_{len-1}到w_{1}, ..., w_{len}。

**Comment by Baixiaobai201619707** [comment]
> > > > @zhangxuying1004 谢谢您！我直接使用了您提供的在线测试特征和预训练模型，发现生成的描述有些是不全的，像是被截断了，请问您遇到过这种情况吗，还是因为我哪里操作不当呢？
> > > 
> > > 
> > > 您好，您说的这个情况我也遇到了。主要原因应该是[meshed-memory-transformer](https://github.com/aimagelab/meshed-memory-transformer)提供的这套代码训练模型时，对于每一个标注的句子，没有考虑，这种方式学得的模型在测试时可能会倾向于生成那些高频/容易预测的单词并且把低频词当成提前结束。
> > 
> > 
> > 请问您可以提供一下您的解决方案吗？谢谢！
> 
> 可以试一下，在模型训练时，对于每一个句子，让解码器的最后一个时间步预测，即根据 bos, w_{1} ... w_{len} 依次预测w_{1} ... w_{len}, eos，而不是现在的 bos, w_{1}, ... ,w_{len-1}到w_{1}, ..., w_{len}。

好的，谢谢您！
