### ISSUE TITLE
关于 online test 代码

### ISSUE THREAD

**Issue by amazingYX** [zhangxuying1004/RSTNet#44]
非常感谢作者能够将这么好的工作开源出来，并且还提供了 online test 的代码。但是我在 online test 代码中发现模型有4个权重，
![image](https://user-images.githubusercontent.com/44744248/175490405-f3b897f5-1cba-4f2a-81f1-bf95ed3ffa9b.png)

请问你论文中 online test 的结果是多个模型集成后的结果吗，我在你的论文中没有找到相关的描述。非常期待你的回复！

**Comment by zhangxuying1004** [comment]
> 非常感谢作者能够将这么好的工作开源出来，并且还提供了 online test 的代码。但是我在 online test 代码中发现模型有4个权重， ![image](https://user-images.githubusercontent.com/44744248/175490405-f3b897f5-1cba-4f2a-81f1-bf95ed3ffa9b.png)
> 
> 请问你论文中 online test 的结果是多个模型集成后的结果吗，我在你的论文中没有找到相关的描述。非常期待你的回复！

您好，我论文中online test的结果是4个模型集成的结果，论文4.3 Online Evaluation 中说明了。

**Comment by amazingYX** [comment]
不好意思，是我没看仔细了，打扰了
