### ISSUE TITLE
TypeError: 'generator' object is not callable

### ISSUE THREAD

**Issue by cui0204** [zhangxuying1004/RSTNet#45]
Hello, thanks for sharing the code. This error occurs when I am running offline tests. What happens? I haven't found a solution yet. Thank you very much for your help.
![error](https://user-images.githubusercontent.com/102974435/175810591-ce1b412f-496d-44f0-a533-8f4e52e4de08.GIF)

**Comment by zhangxuying1004** [comment]
> Hello, thanks for sharing the code. This error occurs when I am running offline tests. What happens? I haven't found a solution yet. Thank you very much for your help. ![error](https://user-images.githubusercontent.com/102974435/175810591-ce1b412f-496d-44f0-a533-8f4e52e4de08.GIF) [ ![error](https://user-images.githubusercontent.com/102974435/175810591-ce1b412f-496d-44f0-a533-8f4e52e4de08.GIF) ](https://user-images.githubusercontent.com/102974435/175810591-ce1b412f-496d-44f0-a533-8f4e52e4de08.GIF) [ ](https://user-images.githubusercontent.com/102974435/175810591-ce1b412f-496d-44f0-a533-8f4e52e4de08.GIF)

Thanks for your attention. 
please check if your dataset has been loaded successfully?

**Comment by zhangxuying1004** [comment]
> Hello, thanks for sharing the code. This error occurs when I am running offline tests. What happens? I haven't found a solution yet. Thank you very much for your help. ![error](https://user-images.githubusercontent.com/102974435/175810591-ce1b412f-496d-44f0-a533-8f4e52e4de08.GIF) [ ![error](https://user-images.githubusercontent.com/102974435/175810591-ce1b412f-496d-44f0-a533-8f4e52e4de08.GIF) ](https://user-images.githubusercontent.com/102974435/175810591-ce1b412f-496d-44f0-a533-8f4e52e4de08.GIF) [ ](https://user-images.githubusercontent.com/102974435/175810591-ce1b412f-496d-44f0-a533-8f4e52e4de08.GIF)

Thanks for your attention.
please check if your dataset has been loaded successfully?

**Comment by zhangxuying1004** [comment]
> Hello, thanks for sharing the code. This error occurs when I am running offline tests. What happens? I haven't found a solution yet. Thank you very much for your help. ![error](https://user-images.githubusercontent.com/102974435/175810591-ce1b412f-496d-44f0-a533-8f4e52e4de08.GIF) 

Thanks for your attention.
please check if your dataset has been loaded successfully?

**Comment by CAU-ISS-Lab** [comment]
I have tackled this problem in the "training stage". You should modify the "fetch.py" as following:
![微信截图_20230507003916](https://user-images.githubusercontent.com/33824377/236636418-a31175a6-7338-4db9-86f5-a3b2dbcbeaeb.png)
and, use "enumerate(dataloader)" rather than "enumerate(iter(dataloader))"
