### ISSUE TITLE
question about warning

### ISSUE THREAD

**Issue by Sandy12345666** [zhangxuying1004/RSTNet#46]
hello,author.I have two question about your code.
1.In the field.py, you import default_collate,but there is no default_collate in the dataloader.

![8734feb910e774f1b4a2f6df6f2a183](https://user-images.githubusercontent.com/89297479/178181578-2fb5ce02-bdd3-477c-a294-0bc0b2d3077c.jpg)
2.Could you tell me how to deal the User warning,thank you.
![a854f5e503e4ce27d45e19f57812dbf](https://user-images.githubusercontent.com/89297479/178181766-268305a0-c5a6-473c-8e18-c16027cc5382.jpg)

**Comment by hzf-hhh** [comment]
the same warning, did you resolve?

**Comment by zhangxuying1004** [comment]
> 

Thanks for your attention.
1. the version of your pytorch?
2. Uncomment line 110 and comment line 111 in ./data/field.py

**Comment by yiren-jian** [comment]
try `python -W ignore train.py`
