### ISSUE TITLE
online test 提交

### ISSUE THREAD

**Issue by amazingYX** [zhangxuying1004/RSTNet#47]
非常抱歉再次打扰你，我使用你开源的 test_online 代码生成两个 json 文件并提交后，并没有顺利给出分数，反而报错了：
![image](https://user-images.githubusercontent.com/44744248/182327110-0174d1a5-b9b0-4339-b65b-51064c029aea.png)
请问你有遇到过这个问题吗。我是在 win11 系统下把两个 json 文件放到 result 文件夹下，然后打包成 zip 文件：
![image](https://user-images.githubusercontent.com/44744248/182327557-8fed0d39-9549-429a-a3ea-9ff1852dfb13.png)
是我文件结构有问题吗？非常期待你的回复

**Comment by amazingYX** [comment]
文件结构除了点问题，已解决，打扰了

**Comment by Red-George** [comment]
想请问一下最终结构是什么样子的，碰见了同样麻烦。 @amazingYX

**Comment by amazingYX** [comment]
> 想请问一下最终结构是什么样子的，碰见了同样麻烦。 @amazingYX

不能再叠加一层result文件夹。result.zip下直接就是生成的两个json文件
![image](https://github.com/zhangxuying1004/RSTNet/assets/44744248/cea52693-471c-46d9-8fff-945d2d3c4bb0)

**Comment by Red-George** [comment]
> > 想请问一下最终结构是什么样子的，碰见了同样麻烦。 @amazingYX
> 
> 不能再叠加一层result文件夹。result.zip下直接就是生成的两个json文件 ![image](https://private-user-images.githubusercontent.com/44744248/310328491-cea52693-471c-46d9-8fff-945d2d3c4bb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2ODg4NzEsIm5iZiI6MTcwOTY4ODU3MSwicGF0aCI6Ii80NDc0NDI0OC8zMTAzMjg0OTEtY2VhNTI2OTMtNDcxYy00NmQ5LThmZmYtOTQ1ZDJkM2M0YmIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDAxMjkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyZWNhZGZmMmFhMTQzNWQ1MmZkNzI1ZjU1YWQyMDk2Njg3NGMzMjZiNGVmMDhiMGJlYzFjZDg3YzM4ZTkyMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UlzxyTgsh9BumbPHYO_FqlmtkEaMj0hYT6R7Y_naGVU)

解决了，感谢！！！
