### ISSUE TITLE
Some question about custom dataset

### ISSUE THREAD

**Issue by zml110120** [zhangxuying1004/RSTNet#48]
Dear author @zhangxuying1004 ,
         It is a wonderful work. If my own dataset have not Object Detection Annotation, how can i use your model?

**Comment by zhangxuying1004** [comment]
> Dear author @zhangxuying1004 , It is a wonderful work. If my own dataset have not Object Detection Annotation, how can i use your model?

Thanks for your attention. Actually, you don't need the 'Object Detection Annotation' when you use my model. You just need to extract visual features of your dataset according to [grid-feats-vqa](https://github.com/facebookresearch/grid-feats-vqa) and switch them according to this project's README. You also need to replace the original visual features with yours. Then you can use my model no matter you want to infer captions or finetune on your dataset.
