### ISSUE TITLE
请问用您的environment.yml创建conda环境时总是报各种依赖冲突，请问这种情况该如何解决呢？感谢

### ISSUE THREAD

**Issue by Rain722** [zhangxuying1004/RSTNet#49]
![image](https://user-images.githubusercontent.com/34411335/190108794-8360e250-e81b-4ecb-b3c1-1bb8d885f969.png)

**Comment by zhangxuying1004** [comment]
> ![image](https://user-images.githubusercontent.com/34411335/190108794-8360e250-e81b-4ecb-b3c1-1bb8d885f969.png)

您好，有一个简单的方法您可以尝试以下，先安装指定pytorch和torchvision，然后直接运行程序，根据提示需要什么装什么。
