### ISSUE TITLE
关于X152_grid_feature文件

### ISSUE THREAD

**Issue by zhouMail** [zhangxuying1004/RSTNet#52]
你好，可以发一下X152的特征文件吗？

**Comment by zhangxuying1004** [comment]
> 你好，可以发一下X152的特征文件吗？

您好，这个特征文件比较大，我目前想到两种解决方案，一是您寄一个硬盘给我，我把文件拷贝后发给您，二是我把这两个文件分段上传到百度网盘里，然后提供一个合并脚本。

**Comment by zhouMail** [comment]
您好，我需要的是X152_grid_feats_coco_trainval.hdf5和X152_grid_feats_coco_test.hdf5这两个文件，大概应该是60G的样子，您的百度网盘如果可以装的下的话，可以分享一个连接给我。

**Comment by zhangxuying1004** [comment]
> 您好，我需要的是X152_grid_feats_coco_trainval.hdf5和X152_grid_feats_coco_test.hdf5这两个文件，大概应该是60G的样子，您的百度网盘如果可以装的下的话，可以分享一个连接给我。

OK，我处理一下，明天或者后天放到这个project的readme里。

**Comment by zhouMail** [comment]
好的，非常感谢！

**Comment by zhangxuying1004** [comment]
百度网盘链接：https://pan.baidu.com/s/1myelTYJE8a1HDZHkoccfIA，提取码：cvpr

**Comment by zhangxuying1004** [comment]
百度网盘链接：https://pan.baidu.com/s/1myelTYJE8a1HDZHkoccfIA
提取码：cvpr
