### ISSUE TITLE
关于supplementary material

### ISSUE THREAD

**Issue by klslord** [zhangxuying1004/RSTNet#53]
您好，我看到您在原论文3.1章节中提到具体计算过程在补充材料中，但是我在CVPR官网中没有找到补充材料对应的下载链接，能麻烦您提供一下补充材料吗

**Comment by zhangxuying1004** [comment]
> 您好，我看到您在原论文3.1章节中提到具体计算过程在补充材料中，但是我在CVPR官网中没有找到补充材料对应的下载链接，能麻烦您提供一下补充材料吗

可以，发一下您的邮箱，我邮件发你。

**Comment by klslord** [comment]
我的邮箱是klslord@163.com

**Comment by klslord** [comment]
> 
我的邮箱是klslord@163.com
