### ISSUE TITLE
关于ResNext152数据集和spice指标

### ISSUE THREAD

**Issue by bacon-yu** [zhangxuying1004/RSTNet#54]
你好，先生，我请教两个问题，请问一下ResNext152数据集可以在哪里得到，还有那个spice指标怎么显示。希望能得到您的回复，感激不尽。

**Comment by zhangxuying1004** [comment]
> 你好，先生，我请教两个问题，请问一下ResNext152数据集可以在哪里得到，还有那个spice指标怎么显示。希望能得到您的回复，感激不尽。

问题1: 我在readme里给的百度网盘链接中有，您可以自己去下载。
问题2: 考虑到训练时的速度，我把evaluation中spice指标去掉了，您可以前往[pycocoevalcap](https://github.com/tylin/coco-caption/tree/master/pycocoevalcap)，把spice放置到evaluation中，在[__init__.py](https://github.com/zhangxuying1004/RSTNet/blob/master/evaluation/__init__.py)中加入spice评价即可。不过建议您训练时不要加，到测试时再加。

**Comment by bacon-yu** [comment]
非常谢谢您的回复，让我解决了spice指标的问题；您给出的网盘链接有密码，请问一下网盘链接的密码是什么

**Comment by bacon-yu** [comment]
> > 你好，先生，我请教两个问题，请问一下ResNext152数据集可以在哪里得到，还有那个香料指标怎么显示。希望能得到您的回复，感激不尽。
> 
> 问题1： 我在readme里给的百度网盘链接中有，您可以自己去下载。 问题2： 考虑到训练时的速度，我把evaluation中spice指标去掉了，您可以前往[pycoevalcap](https://github.com/tylin/coco-caption/tree/master/pycocoevalcap)，把spice放置到evaluation中，在[**init**.py](https://github.com/zhangxuying1004/RSTNet/blob/master/evaluation/__init__.py)中加入spice评价即可。不过建议您训练时不要加，到测试时再加。

非常谢谢您的回复，让我解决了spice指标的问题；您给出的网盘链接有密码，请问一下网盘链接的密码是什么

**Comment by zhangxuying1004** [comment]
> > > 你好，先生，我请教两个问题，请问一下ResNext152数据集可以在哪里得到，还有那个香料指标怎么显示。希望能得到您的回复，感激不尽。
> > 
> > 
> > 问题1： 我在readme里给的百度网盘链接中有，您可以自己去下载。 问题2： 考虑到训练时的速度，我把evaluation中spice指标去掉了，您可以前往[pycoevalcap](https://github.com/tylin/coco-caption/tree/master/pycocoevalcap)，把spice放置到evaluation中，在[**init**.py](https://github.com/zhangxuying1004/RSTNet/blob/master/evaluation/__init__.py)中加入spice评价即可。不过建议您训练时不要加，到测试时再加。
> 
> 非常谢谢您的回复，让我解决了spice指标的问题；您给出的网盘链接有密码，请问一下网盘链接的密码是什么

readme里有。
