### ISSUE TITLE
Run for Custom dataset

### ISSUE THREAD

**Issue by ayushsingh11** [zhangxuying1004/RSTNet#55]
I have a `X101_grid_feats_coco_test.hdf5` file, and a corresponding `instances_val.json` file which consists of the true labels. The hdf5 file was created after running grid-feats-vqa and feats_process.py. My aim is to get metrics for this dataset.
Upon running `!python test_offline.py --features_path='./datasets/X101-features/X101_grid_feats_coco_test.hdf5' --annotation_folder='./datasets/annotations'`, I am getting the following error - 
<img width="908" alt="Screen Shot 2023-02-15 at 2 39 21 AM" src="https://user-images.githubusercontent.com/30299945/219004673-df587b69-bf29-421d-8346-e9f532080313.png">

When I use the annotations folder of COCO, then I get the following error instead - 
<img width="922" alt="Screen Shot 2023-02-15 at 2 38 57 AM" src="https://user-images.githubusercontent.com/30299945/219004580-0529f117-d43e-4adc-9f87-53e84f636811.png">

Can you please share what changes should I make to run the given code for a custom dataset?

**Comment by CAU-ISS-Lab** [comment]
https://github.com/zhangxuying1004/RSTNet/issues/45#issuecomment-1537178364

I have tackled this problem. The details are from above link.
