### ISSUE TITLE
ImportError: cannot import name 'TensorRecorder'

### ISSUE THREAD

**Issue by WUHE-art** [zhangxuying1004/RSTNet#6]
您好，当我运行train_transformer.py文件时, "from middle import TensorRecorder"这句出现了问题. ImportError: cannot import name 'TensorRecorder'. 我已经安装了middle包, 但是不知道错误出在哪里。

**Comment by zhangxuying1004** [comment]
> 您好，当我运行train_transformer.py文件时, "from middle import TensorRecorder"这句出现了问题. ImportError: cannot import name 'TensorRecorder'. 我已经安装了middle包, 但是不知道错误出在哪里。
您好，middle这个包用不到，把attention.py文件中的第6行和第8行注释掉即可。非常抱歉给您带来了麻烦，我接下来会把无关的代码删掉。

**Comment by zhangxuying1004** [comment]
> 您好，当我运行train_transformer.py文件时, "from middle import TensorRecorder"这句出现了问题. ImportError: cannot import name 'TensorRecorder'. 我已经安装了middle包, 但是不知道错误出在哪里。

您好，middle这个包用不到，把attention.py文件中的第6行和第8行注释掉即可。非常抱歉给您带来了麻烦，我接下来会把无关的代码删掉。

**Comment by WUHE-art** [comment]
您好，当我训练模型时，遇到了如下问题: Exception ignored in: <data.utils.DummyFile object at 0x7fbbf0ce4860>
AttributeError: 'DummyFile' object has no attribute 'flush'. 目前我没有找到一个很好的解决办法. 期待您的回复.

**Comment by zhangxuying1004** [comment]
> 您好，当我训练模型时，遇到了如下问题: Exception ignored in: <data.utils.DummyFile object at 0x7fbbf0ce4860> AttributeError: 'DummyFile' object has no attribute 'flush'. 目前我没有找到一个很好的解决办法. 期待您的回复.

您好，这个问题解决了吗？我没有遇到这个问题，可以定位到哪段代码报的这个错误吗？麻烦告知一下。
