### ISSUE TITLE
Supplementary Material

### ISSUE THREAD

**Issue by harshraj22** [zhangxuying1004/RSTNet#7]
@zhangxuying1004  where is the supplementary material that you talk about in [section 3.1](https://openaccess.thecvf.com/content/CVPR2021/papers/Zhang_RSTNet_Captioning_With_Adaptive_Attention_on_Visual_and_Non-Visual_Words_CVPR_2021_paper.pdf) about specific calculations of 2d relative position of each grid ?

![image](https://user-images.githubusercontent.com/46635452/130246440-3ef0d853-c0a2-477b-92f9-3889468fc5e0.png)

**Comment by zhangxuying1004** [comment]
Thanks for your attention. You can refer to the implement in models/rstnet/utils.py. I will provide a revised version of this paper which contains the contents of supplementary material on arXiv.

**Comment by zhangxuying1004** [comment]
> @zhangxuying1004 where is the supplementary material that you talk about in [section 3.1](https://openaccess.thecvf.com/content/CVPR2021/papers/Zhang_RSTNet_Captioning_With_Adaptive_Attention_on_Visual_and_Non-Visual_Words_CVPR_2021_paper.pdf) about specific calculations of 2d relative position of each grid ?
> 
> ![image](https://user-images.githubusercontent.com/46635452/130246440-3ef0d853-c0a2-477b-92f9-3889468fc5e0.png)

Thanks for your attention. You can refer to the implement in models/rstnet/utils.py. I will provide a revised version of this paper which contains the contents of supplementary material on arXiv.
