### ISSUE TITLE
Issues when trying to set up environment m2release

### ISSUE THREAD

**Issue by hungnt14** [zhangxuying1004/RSTNet#9]
I use conda on Google Colab, not my local.

When I was creating the environment, It couldn't found these packages:
![image](https://user-images.githubusercontent.com/33962566/133954734-00a15c6c-f926-4ac7-8d06-3ff77dfe97ec.png)

I try to delete these dependencies from environment.yml, and start to create the environment again, it was successfully installed, but when I activate the m2release env, an error happened:

![image](https://user-images.githubusercontent.com/33962566/133954848-fc655f90-9374-4e48-89f3-bfe024c63154.png)

I can't figure out what's wrong, hope someone can help me to solve it.

Much thanks.

**Comment by zhangxuying1004** [comment]
> I use conda on Google Colab, not my local.
> 
> When I was creating the environment, It couldn't found these packages:
> ![image](https://user-images.githubusercontent.com/33962566/133954734-00a15c6c-f926-4ac7-8d06-3ff77dfe97ec.png)
> 
> I try to delete these dependencies from environment.yml, and start to create the environment again, it was successfully installed, but when I activate the m2release env, an error happened:
> 
> ![image](https://user-images.githubusercontent.com/33962566/133954848-fc655f90-9374-4e48-89f3-bfe024c63154.png)
> 
> I can't figure out what's wrong, hope someone can help me to solve it.
> 
> Much thanks.

First, you can try to reinstall you anaconda.
Then, you can run this project directly, and install the missing package according to the error message.

**Comment by hungnt14** [comment]
I've search this package and there is no package name "intel-openmp==2019.5=281".

Did you forget updating your environment.yml?

**Comment by hungnt14** [comment]
I've search this package and there is no package name "intel-openmp==2019.5=281".

Did you forget updating your environment.yml?

**Comment by zhangxuying1004** [comment]
> I've search this package and there is no package name "intel-openmp==2019.5=281".
> 
> Did you forget updating your environment.yml?

This package setting is provided by m2 code, you can just try to install intel-openmp without specifying the version.

**Comment by hungnt14** [comment]
@zhangxuying1004 Thanks for your help!

By the way, can I train this model on a my custom dataset (in COCO format as well)?

**Comment by zhangxuying1004** [comment]
> @zhangxuying1004 Thanks for your help!
> 
> By the way, can I train this model on a my custom dataset (in COCO format as well)?

Of course you can. 
First, you need to extract image features and save them in a h5py file, please refer to feats_process.py.
Second, you need to save image captions in json files, please refer to coco files.

**Comment by hungnt14** [comment]
"Then, visual features are computed with the code provided by [2]"

I ask this question because I wondered the code you mentioned is [this](https://github.com/peteanderson80/bottom-up-attention) repo?
